services:

  mysql:
    image: mysql:8.0
    container_name: my-mysql-student-college
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Root@1234
      MYSQL_DATABASE: college_student_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.4
    container_name: keycloak
    command:
      - start-dev
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak_db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - "8085:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  college-service:
    build:
      context: ./CollegeService
      dockerfile: Dockerfile
    image: college-service:latest
    container_name: college-service
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/college_student_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@1234
    ports:
      - "8082:8082"
    networks:
      - app-network

  student-service:
    build:
      context: ./StudentService
      dockerfile: Dockerfile
    image: student-service:latest
    container_name: student-service
    depends_on:
      mysql:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/college_student_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root@1234
    ports:
      - "8081:8081"
    networks:
      - app-network

  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      - student-service
      - college-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_APPLICATION_NAME=ApiGateway
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
