server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/college-student-demo/protocol/openid-connect/certs

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: http://student-service:8081
          predicates:
            - Path=/student/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: college-service
          uri: http://college-service:8082
          predicates:
            - Path=/college/**
          filters:
            - RemoveRequestHeader=Cookie

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: student-service
        url: /student/v3/api-docs
      - name: college-service
        url: /college/v3/api-docs

logging:
  level:
    org.springframework.cloud.gateway: INFO
